version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    # Group minor and patch updates
    groups:
      production-dependencies:
        patterns:
          - "react*"
          - "@google/genai"
      development-dependencies:
        patterns:
          - "@types/*"
          - "@vitejs/*"
          - "typescript"
          - "vite"
    # Allow up to 10 open pull requests
    open-pull-requests-limit: 10
    # Auto-merge patch updates for development dependencies
    reviewers:
      - "Joedaddy66"
    assignees:
      - "Joedaddy66"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "security"
    
  # Enable security updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "github-actions"
      - "security"