name: CI/CD Production Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  NODE_VERSION: '22.12'

permissions:
  contents: read

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run TypeScript type check
        run: npx tsc --noEmit || echo "⚠️ TypeScript errors found - review recommended"
        continue-on-error: true
        
      - name: Check for console.log statements
        run: |
          if grep -r "console\.log" --include="*.ts" --include="*.tsx" --exclude-dir=node_modules --exclude-dir=dist .; then
            echo "⚠️ Warning: console.log statements found in code"
            echo "Consider removing them for production or using a proper logging library"
          else
            echo "✅ No console.log statements found"
          fi
        continue-on-error: true

  build:
    name: Build Application
    runs-on: ubuntu-latest
    needs: lint
    permissions:
      contents: read
      actions: write  # For artifact upload
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build for production
        run: npm run build
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          REACT_APP_ADAPTER_API_BASE: ${{ secrets.REACT_APP_ADAPTER_API_BASE }}
        
      - name: Verify build artifacts
        run: |
          echo "Checking build artifacts..."
          if [ -d "dist" ]; then
            echo "✅ Build successful - dist folder created"
            ls -la dist/
            echo "Build contents:"
            du -sh dist/*
          else
            echo "❌ Build failed - no dist folder found"
            exit 1
          fi
          
      - name: Upload build artifacts
        uses: actions/upload-artifact@v5
        with:
          name: production-build
          path: dist/
          retention-days: 7

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: read
      actions: read  # For artifact download
      pull-requests: write  # For commenting on PRs
    environment:
      name: production
      url: ${{ steps.deployment.outputs.url }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: production-build
          path: dist/
          
      - name: Deploy to Vercel
        id: deployment
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prod'
          working-directory: ./
          
      - name: Deployment Status
        run: |
          echo "🚀 Deployment completed successfully!"
          echo "📍 URL: ${{ steps.deployment.outputs.url }}"
          
      - name: Comment PR with deployment URL
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🚀 Preview deployed to: ${{ steps.deployment.outputs.url }}'
            })

  health-check:
    name: Post-Deployment Health Check
    runs-on: ubuntu-latest
    needs: deploy
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: read
    
    steps:
      - name: Wait for deployment to be ready
        run: sleep 30
        
      - name: Health Check
        run: |
          echo "🏥 Running health check..."
          # Add your health check endpoint here when available
          # Example: curl -f https://your-app-url.vercel.app/health || exit 1
          echo "✅ Health check passed (configure actual endpoint when available)"
